name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: diyaxbudhia
          outputs: |
            # Black background (no-contribution cells), white snake, pink/purple/teal contributions
            dist/github-contribution-grid-snake.svg?color_back=%23000000&color_snake=%23FFFFFF&color_dots=%23F472B6,%237C3AED,%2338B2AC
            dist/github-contribution-grid-snake-dark.svg?color_back=%23000000&color_snake=%23FFFFFF&color_dots=%23F472B6,%237C3AED,%2338B2AC

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
