name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: diyaxbudhia
          outputs: |
              # Light (uses subtle bg, neon accents)
              dist/github-contribution-grid-snake.svg?color_snake=%237C3AED&color_dots=%2338B2AC,%237C3AED,%23F472B6
              # Dark (explicit dark bg, neon accents)
              dist/github-contribution-grid-snake-dark.svg?color_snake=%237C3AED&color_dots=%2338B2AC,%238B5CF6,%23F472B6&color_back=%230D1117

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
